version: '3.7'
services:
  redpanda:
    image: vectorized/redpanda:v23.1.3
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 512M
      - --overprovisioned
      - --node-id 0
      - --check=false
    ports:
      - "9092:9092"
      - "9644:9644"
    networks:
      - redpanda-net

networks:
  redpanda-net:
    driver: bridge
